"""Initial schema revision for PropFlow PM OS

Revision ID: 2643db243b12
Revises: 
Create Date: 2026-08-06 03:34:06.707217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2643db243b12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.alter_column('management_fee_pct',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('reserve_fund_pct',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_financial_records_id'))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_id'))

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_work_orders_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_id'), ['id'], unique=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_id'), ['id'], unique=False)

    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_records_id'), ['id'], unique=False)
        batch_op.alter_column('reserve_fund_pct',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('management_fee_pct',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
